#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    path: D:\MyCode\log
#  level:
#    com.imook.sell.loggerTest: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://172.20.10.7/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.0.107/sell?characterEncoding=utf-8&useSSL=false

  #    192.168.0.105     172.20.10.7

  jpa:
      show-sql: true
server:
  servlet:
    context-path: /sell
